### ISSUE TITLE
Resource vault_consul_secret_backend thinks token is unspecified (but exists from data source).

### ISSUE THREAD

**Issue by tristanmorgan** [hashicorp/terraform-provider-vault#1595] opened 2022-09-05 01:26 UTC
### Terraform Version
Terraform v1.2.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/consul v2.15.1
+ provider registry.terraform.io/hashicorp/vault v3.8.2

### Affected Resource(s)
- vault_consul_secret_backend

### Terraform Configuration Files
```hcl
resource "consul_acl_token" "vault" {
  description = "Token for Vault secrets engine."
  policies    = ["global-management"]
}

data "consul_acl_token_secret_id" "vault" {
  accessor_id = consul_acl_token.vault.id
}

resource "vault_consul_secret_backend" "consul" {
  path        = "consul"
  description = "Access Consul tokens"

  address                   = "127.0.0.1:8500"
  scheme                    = "http"
  token                     = data.consul_acl_token_secret_id.vault.secret_id
  bootstrap                 = false
  default_lease_ttl_seconds = "3600"
  max_lease_ttl_seconds     = "36000"
}
```

### Expected Behavior
The token for the vault secrets backend is being retrieved via a data source that is "known after apply". the expected behaviour is for the code to apply successfully. 

### Actual Behavior
When the configuration is attempting to plan or apply the following message is returned.
```
│ Error: field 'bootstrap' must be set to true when 'token' is unspecified
```

### Steps to Reproduce
using the code provided
1. `terraform apply`

### Important Factoids
Consul's ACL system has been bootstrapped previously and a valid ACL token is available in the environment variables.

**Comment by tristanmorgan** [comment] 2022-09-05 01:38
### Additional information
if you set bootstrap to true and apply anyway, you get this error:
```
│ Error: field 'bootstrap' must be set to false when 'token' is specified
```

**Comment by robmonte** [comment] 2022-09-07 20:31
Hi Tristan, thank you for reporting this. I'm going to take a look and can give you an update when I have some information to share.

**Comment by robmonte** [comment] 2022-09-08 19:48
We have a tentative bug fix for this. Thanks for bringing light to the issue! 👍

**Closed** 2022-09-09 21:49 UTC
Labels: bug

**Comment by tristanmorgan** [comment] 2022-09-11 22:01
thanks @robmonte.

**Comment by robmonte** [comment] 2022-09-11 22:14
@tristanmorgan Happy to help! Once the bugfix goes out in a release, please feel free to confirm if the issue is resolved for you or if you still have any problems!
