### ISSUE TITLE
Missing strict ordering: vault_mount must happen before vault_generic_secret (at least for PKI backend)

### ISSUE THREAD

**Issue by andrejvanderzee** [hashicorp/terraform-provider-vault#71] opened 2018-02-09 09:07 UTC
### Terraform Version
$ terraform -v
Terraform v0.11.3
+ provider.vault v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_mount
- vault_generic_secret

### Terraform Configuration Files
```hcl
provider "vault" { }

resource "vault_mount" "team5_k8s_apiserver" {

  path = "team5/k8s-apiserver"
  type = "pki"
}

resource "vault_generic_secret" "team5_k8s_apiserver_ca" {

  path = "team5/k8s-apiserver/root/generate/internal"

  data_json = <<EOT
{
  "common_name": "xxx.io"
}
EOT
}
```

### Debug Output
https://gist.github.com/andrejvanderzee/5fdd73fcd507e7c7375b7fad833ffba1

### Expected Behavior
Strict ordering: First create `vault_mount`, then `vault_generic_secret`. Note that for `terraform destroy` I would expect the same reverse order (fist destroy `vault_generic_secret`, then `vault_mount`).

### Actual Behavior
Parallel creation resulting `vault_generic_secret` to fail, cause it requires `vault_mount` first. Note that the same holds for `terraform destroy` only in reverse order (`vault_generic_secret` fails because the PKI backend is already unmounted).

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by therealbill** [comment] 2018-02-15 17:50
The problem is that TF has no way to know that your second resource depends on the first. One option would be to reference the mount's path in defining the secret's path definition. For example, 
`path = "${vault_mount.team5_k8s_apiserver.path}/root/generate/internal"`

By doing so you tell Terraform that the second resource requires the first, and they should be done serially.

Alternatively you could use `depends_on`  to specify the relationship w/o using interpolation in the path. Personally, I'd prefer the interpolation route. Doing so allows you to change it in one location, should you want to, rather than tracking them down. Ultimately either way you're letting Terraform know that resource B needs resource A and that is the critical information it needs to make the decision.

**Comment by phinze** [comment] 2018-03-18 18:37
Thanks for filing this! I just bumped into it myself. @therealbill your answer is spot-on - I'm applying the dependency-ordering-via-interpolation workaround to my config right now.

It still would be nice if Terraform could sort out these implicit dependencies between certain kinds of resources. I believe that would require a new core <-> provider API. It's definitely worth considering. I'll chat with the TF core folks about it at some point. 💭 👍

**Comment by syndbg** [comment] 2018-04-15 12:42
@phinze https://www.terraform.io/intro/getting-started/dependencies.html#implicit-and-explicit-dependencies

**Comment by phinze** [comment] 2018-04-16 14:15
Ah thanks @syndbg I had forgotten we call dependencies created via interpolation "implicit dependencies". I guess the potential feature I was referring to was more like "automatic dependencies" whereby Terraform would recognize that resources of a certain type need to always follow resources of another type given certain matching attributes. Just me musing on potential core functionality. 😄

In the meantime - using interpolation to draw "implicit dependencies" is the way to go!

**Comment by syndbg** [comment] 2018-04-16 14:28
Yep, it would be easier for use, but overall increase the complexity of the code greatly.

**Comment by benashz** [comment] 2022-06-03 18:20
Terraform itself is responsible for managing the dependency graph. If one resource references an attribute of another, that resource will be created first e.g:

```hcl

resource "vault_generic_secret" "team5_k8s_apiserver_ca" {
  path = "${vault_mount.team5_k8s_apiserver.path}/root/generate/internal"

  data_json = <<EOT
{
  "common_name": "xxx.io"
}
EOT
}
```

Closing this out as it is not a provider issue.

**Closed by benashz** 2022-06-03 18:20 UTC
Labels: question
