### ISSUE TITLE
Crash on v2.20.0

### ISSUE THREAD

**Issue by unredundant** [hashicorp/terraform-provider-vault#1064] opened 2021-05-31 17:22 UTC
### Terraform Version
0.15.4

### Affected Resource(s)
Seems to be pretty much anything/everything

### Terraform Configuration Files
```hcl
resource "vault_mount" "kv-internal" {
  path        = "internal"
  type        = "kv-v2"
  description = "KV Store for internal secrets"
}

data "vault_policy_document" "read_cortex_ci_cd_secrets" {
  rule {
    path         = "internal/*"
    capabilities = ["create", "read", "list"]
    description  = "create and read all internal secrets"
  }
}

resource "vault_policy" "read_cortex_ci_cd_secrets" {
  name   = "read_github_action_secrets"
  policy = data.vault_policy_document.read_cortex_ci_cd_secrets.hcl
}
```

### Debug Output
https://gist.github.com/rgbrizzlehizzle/5d8014cde4e9baeca39648f3182fa7b2

### Panic Output
Added to gist above 

### Expected Behavior
Not this lmao

### Actual Behavior
complete crash

### Steps to Reproduce
Just tried to run `tf plan`

### Important Factoids
I run on tf cloud, not sure if that matters 

### References
not that i'm aware of

**Comment by tvoran** [comment] 2021-06-02 01:59
Hi @rgbrizzlehizzle, I'm not able to reproduce this with terraform 0.15.4 and vault running locally, so I'm wondering what your provider and auth_login for vault looks like (sans any sensitive data). And were you using a previous version of the plugin with an existing config and just changed the vault plugin version, or is this a fresh setup?

**Comment by rgbrizzlehizzle** [comment] 2021-06-02 10:33
Tbh I can't help you any more because this was a personal project just for me to learn vault and terraform so I ended up just wiping the whole setup after I got stuck here 😅 

It was a fresh setup as far as vault goes, though I was plugging it into an existing to tf repo with some other existing infra, nothing crazy just a couple of digital ocean configurations. 

Honestly I would have assumed it was an issue with my code if the output hadn't been so adamant that it was a problem with the plug-in itself lol

**Comment by vinay-gopalan** [comment] 2023-05-22 20:24
Hi! Going to close this issue since it also wasn't reproducible on any of the latest versions, and there hasn't been any conversation around it for a while. Please feel free to open another issue if you face any problems, thanks! 🙏🏼

**Closed by vinay-gopalan** 2023-05-22 20:24 UTC
