### ISSUE TITLE
vault_pki_secret_backend_role missing argument `issuer_ref`

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/terraform-provider-vault#1598] opened 2022-09-08 17:04 UTC
### Terraform Version
```
Terraform v1.2.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/vault v3.8.0

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_pki_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_pki_secret_backend_role" "demo" {
    ...
    issuer_ref = "other"
    allow_ip_sans = [...]
    exclude_cn_from_sans = true
}
```

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior

I expect to be able to change some of the Role parameters listed on the [Create/Update Role](https://www.vaultproject.io/api-docs/secret/pki#create-update-role) documentation.

### Actual Behavior

Terraform does not recognize the parameters, there are a few. I've identified a couple in my example above.

```
│ Error: Unsupported argument
│ 
│   on demo.tf line 1, in resource "vault_pki_secret_backend_role" "demo":
│   78:   issuer_ref = "other"
│ 
│ An argument named "issuer_ref" is not expected here.
```

### Steps to Reproduce
1. `terraform plan`

### Important Factoids

I noticed Vault also has a role configuration option `AllowTokenDisplayName` but that doesn't seem to be documented and it's not exposed in any way I can see.  I'm not clear if that's an internal-only configuration.

### References
There are a few missing parameters.
- #1486 
- #1419

**Comment by ANGkeith** [comment] 2022-09-18 18:43
Duplicate of #1510

**Comment by fairclothjm** [comment] 2023-05-15 14:25
Closed by https://github.com/hashicorp/terraform-provider-vault/pull/1845

**Closed by fairclothjm** 2023-05-15 14:25 UTC
