### ISSUE TITLE
Terraform crashes when CRL configuration gets updated for PKI secret backend

### ISSUE THREAD

**Issue by jstachowiak** [hashicorp/terraform-provider-vault#1003] opened 2021-03-17 14:55 UTC
### Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/vault v2.18.0
```

### Affected Resource(s)
- vault_pki_secret_backend_crl_config

### Terraform Configuration Files
```hcl
resource "vault_mount" "pki" {
  path = "pki"
  type = "pki"
}

resource "vault_pki_secret_backend_crl_config" "crl_config" {
  backend = vault_mount.pki.path
  expiry  = "72h"
}
```

### Panic Output
https://gist.github.com/jstachowiak/84621bb6ec3ff828f44afc21a3777e88

### Expected Behavior
When a mounted secret backend is remounted to a new endpoint, Terraform should enable a new secret backend and update CRL configuration accordingly.

### Actual Behavior
Terraform crashes.

### Steps to Reproduce
1. `terraform apply`
2. `vault secrets move pki/ pki_foobar/`
3. `terraform apply` (crash)

**Comment by benashz** [comment] 2022-04-19 19:26
Duplicate of #1299

**Closed by benashz** 2022-04-19 19:26 UTC
Labels: bug, crash, pki-enhancements
