### ISSUE TITLE
vault provider does not use namespace creating child token

### ISSUE THREAD

**Issue by matteomazza91** [hashicorp/terraform-provider-vault#602] opened 2019-11-12 13:07 UTC
### Terraform Version
Terraform v0.12.6
+ provider.vault v2.6.0

### Terraform Configuration Files
main.tf

```hcl
provider "vault" {
  version = "~> 2.6"
  address = "https://MY_VAULT_HOSTNAME/"
  namespace = "MY_NAMESPACE"
  alias   = "my-alias"

  auth_login {
    path = "auth/ldap/login/${var.login_username}"
    parameters = {
      password = var.login_password
    }
  }
}

module "my_test_module" {
  providers = {
    vault = "vault.my-alias"
  }
  source = "./modules/vault/"
}
output "vault_test" {
  value = module.my_test_module.vault_test
}
```

./modules/vault/main.tf

```hcl
data "vault_generic_secret" "vault_secret_test" {
  path = "some/path"
}

output "vault_test" {
  value = data.vault_generic_secret.vault_secret_test.data
}
```

### Debug Output
```
2019-11-12T12:47:48.990Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: -----------------------------------------------------
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: 2019/11/12 12:47:49 [DEBUG] Vault API Request Details:
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: ---[ REQUEST ]---------------------------------------
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: POST /v1/auth/token/create HTTP/1.1
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Host: MY_VAULT_HOSTNAME
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: User-Agent: Go-http-client/1.1
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Content-Length: 128
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: X-Vault-Namespace: 
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: X-Vault-Token: VAULT_TOKEN_CREATED_BY_LOGIN
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Accept-Encoding: gzip
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: 
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: {
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "ttl": "1200s",
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "explicit_max_ttl": "1200s",
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "display_name": "terraform",
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "num_uses": 0,
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "renewable": false,
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "type": "",
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "entity_alias": ""
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: }
2019-11-12T12:47:49.398Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: -----------------------------------------------------

[...]

2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: 2019/11/12 12:47:49 [DEBUG] Vault API Response Details:
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: ---[ RESPONSE ]--------------------------------------
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: HTTP/1.1 403 Forbidden
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Content-Length: 60
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Cache-Control: no-store
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Content-Type: application/json
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Date: Tue, 12 Nov 2019 12:47:49 GMT
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: Strict-Transport-Security: max-age=15638400; includeSubDomains
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: 
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: {
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  "errors": [
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:   "1 error occurred:\n\t* permission denied\n\n"
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4:  ]
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: }
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: 
2019-11-12T12:47:49.584Z [DEBUG] plugin.terraform-provider-vault_v2.6.0_x4: -----------------------------------------------------
2019/11/12 12:47:49 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: failed to create limited child token: Error making API request.
```

### Expected Behavior
set `X-Vault-Namespace` in `/v1/auth/token/create` call. 

### Actual Behavior
`X-Vault-Namespace` is not set

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
possibly related issue:
- https://github.com/terraform-providers/terraform-provider-vault/issues/368

**Comment by Clete2** [comment] 2020-02-12 18:09
Same issue here. Config:

```hcl
provider "vault" {
  address   = "https://my.vault.domain:8200"
  namespace = "org/suborg/mynamespace"
  auth_login {
    path = "auth/k8s-test/login"

    parameters = {
      role      = "my-k8s-role"
      jwt       = var.jwt
    }
  }
}
```

**Comment by Clete2** [comment] 2020-02-12 18:24
Hey OP, the issue is that the Vault provider documentation is lacking.

You need to also put your namespace inside the auth_login block. We found this out by looking at the source code.

```hcl
provider "vault" {
  address   = "https://my.vault.domain:8200"
  namespace = "org/suborg/mynamespace"
  auth_login {
    path      = "auth/k8s-test/login"
    namespace = "org/suborg/mynamespace"

    parameters = {
      role = "myrole"
      jwt  = var.jwt
    }
  }
}
```

**Comment by matteomazza91** [comment] 2020-05-05 12:16
thanks @Clete2 for your workaround. However it's not working for me.

That maybe works if the approle login-method is mounted in the specified workspace. However
in my scenario I use the ldap auth at root level (no namespace) to login.

**Comment by m0ps** [comment] 2020-05-25 11:05
@matteomazza91 in 2.11.0 version **headers** configuration setting was added (https://github.com/terraform-providers/terraform-provider-vault/pull/730). It allows adding additional HTTP headers to all requests. It's useful in such a case, with which you (and me) are faced.
I've switched from LDAP auth to token, and token obtained with auth via API (curl) during running terraform Jenkins job.

**Comment by sacchettom** [comment] 2021-02-25 17:41
@m0ps trying it out in 2.18.0 and it doesn't work. I've tried specifying the header in the provider's configuration, but the one I see being used in trace logs is still empty. I can't seem to find the code where the call is actually manufactured, the interesting point is that the `X-Vault-Namespace` header is always present (even when not added to the provider's configuration) and is always empty on the request for the token.

**Comment by benashz** [comment] 2023-05-02 15:24
Hi @browley86 , sorry to hear that you are having issues with the provider. I believe that #1830 will resolve this issue, since it will take the namespace from `provider{}.namespace` when authenticating with your `auth_login` config.

The provider handles the `namespace` internally, so even if the `X-Vault-Namespace` is set in `headers{}` the value will be overwritten from what is set on `provider{}.namespace`.

**Comment by browley86** [comment] 2023-05-11 15:08
Hey @benashz - Looks like this was merged then rolled back.  Looks like the current PR to fix it is https://github.com/hashicorp/terraform-provider-vault/pull/1841.  Could we please re-open this until that's merged?

**Closed** 2023-06-05 21:02 UTC
