### ISSUE TITLE
Documentation update on vault_database_secret_backend_connection

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-provider-vault#993] opened 2021-03-09 16:47 UTC
### Affected Resource(s)
- vault_database_secret_backend_connection

This issue is for a documentation update to the vault_database_secret_backend_connection resource.

### Expected Behavior
When creating this resource a root username and password are provided in the connection string. It is desirable to provide these as parameters so that they can be rotated using the rotate-root API endpoint. However there is no documentation as to how this is supposed to be accomplished. 

We have found [this comment](https://github.com/hashicorp/terraform-provider-vault/issues/281#issuecomment-456316517) which describes how to do it. This really should be in the documentation.

**Comment by catsby** [comment] 2021-03-12 17:08
Hello there! Thanks for reporting this lack of documentation. After review it seems this is a duplicate of another issue (https://github.com/hashicorp/terraform-provider-vault/issues/644), so I'm going to close this and kindly ask you to track that one for updates. I apologize for the slow response to this documentation issue

**Closed by catsby** 2021-03-12 17:08 UTC
Labels: documentation
