### ISSUE TITLE
Force delete all versions of a secret during destroy

### ISSUE THREAD

**Issue by vishmit123** [hashicorp/terraform-provider-vault#1020] opened 2021-04-09 10:56 UTC
### Affected Resource(s)
vault_generic_secret

Feature request

is there a way to force delete all versions of a secret during destroy? Currently, it destroys only the latest version.

**Comment by briananstett** [comment] 2021-12-06 18:28
I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-vault/issues/760

**Comment by benashz** [comment] 2021-12-06 19:00
Closing as a duplicate of #760

**Closed by benashz** 2021-12-06 19:00 UTC
